#!/usr/bin/env python3
"""Spec tooling for the Formalisation Engine. Standard library only.

The canonical spec lives in spec-src/formalisation-engine-spec.md and is owned by Tom.
This script turns it into small files that are cheap for Claude Code to read:

  build      Regenerate docs/spec/requirements.jsonl and docs/spec/sections/*.md
  show       Print one or more records by ID (globs allowed: 'FR-EXT-*')
  list       Print one line per record, with filters
  coverage   Report which requirements have tests, and whether those tests pass

Examples:
  python3 scripts/spec_tools.py build
  python3 scripts/spec_tools.py build --check        # CI: fail if generated files are stale
  python3 scripts/spec_tools.py show FR-EXT-04 INV-01
  python3 scripts/spec_tools.py show 'FR-EXT-*' --refs
  python3 scripts/spec_tools.py list --kind FR --area EXT --priority M
  python3 scripts/spec_tools.py coverage --milestone M1
  python3 scripts/spec_tools.py coverage --summary
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import re
import sys
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_SRC = ROOT / "spec-src" / "formalisation-engine-spec.md"
SPEC_DIR = ROOT / "docs" / "spec"
INDEX = SPEC_DIR / "requirements.jsonl"
SECTIONS = SPEC_DIR / "sections"
MILESTONES = ROOT / "docs" / "milestones.json"
RESULTS = ROOT / "var" / "req_results.json"
TESTS = ROOT / "tests"

ID_RE = re.compile(r"\b(?:(?:FR|NFR)-[A-Z]{3}-\d{2}|(?:DP|AS|CN|DD|R|OQ|INV)-\d{2}|G\d{1,2})\b")
FULL_ID_RE = re.compile(r"^(?:(?:FR|NFR)-[A-Z]{3}-\d{2}|(?:DP|AS|CN|DD|R|OQ|INV)-\d{2}|G\d{1,2})$")

# Table header -> record key
HEADER_KEYS = {
    "id": "id",
    "requirement": "text",
    "pri": "priority",
    "ver": "verification",
    "principle": "text",
    "assumption": "text",
    "constraint": "text",
    "decision": "text",
    "reason": "reason",
    "risk": "text",
    "likelihood": "likelihood",
    "impact": "impact",
    "mitigation": "mitigation",
    "question": "text",
    "proposed approach": "proposed",
    "invariant": "text",
    "test": "text",
    "pass condition": "pass_condition",
}

# Kinds that count towards test coverage. INV and G have no priority column in the
# spec; they are treated as Must-have and automatically tested (NFR-SAF-03, 7.3).
COVERAGE_KINDS = {"FR", "NFR", "INV", "G"}
GENERATED_NOTE = (
    "<!-- Generated by scripts/spec_tools.py from spec-src/formalisation-engine-spec.md. "
    "Do not edit; change the source spec and run `python3 scripts/spec_tools.py build`. -->\n\n"
)


# --------------------------------------------------------------------------- parsing


def kind_of(rid: str) -> str:
    if rid.startswith("NFR-"):
        return "NFR"
    if rid.startswith("FR-"):
        return "FR"
    if re.match(r"^G\d", rid):
        return "G"
    return rid.split("-")[0]


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def section_filename(heading: str) -> str:
    """'## 5. Functional requirements' -> '05-functional-requirements.md'."""
    title = heading.lstrip("#").strip()
    m = re.match(r"^(\d+)\.\s+(.*)$", title)
    if m:
        return f"{int(m.group(1)):02d}-{slugify(m.group(2))}.md"
    m = re.match(r"^Appendix\s+([A-Z])\.\s+(.*)$", title)
    if m:
        return f"appendix-{m.group(1).lower()}-{slugify(m.group(2))}.md"
    return f"{slugify(title)}.md"


def split_cells(line: str) -> list[str]:
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|"):
        body = body[:-1]
    body = body.replace("\\|", "\x00")
    return [c.replace("\x00", "|").strip() for c in body.split("|")]


def is_separator(line: str) -> bool:
    cells = split_cells(line)
    return bool(cells) and all(re.fullmatch(r":?-{3,}:?", c) for c in cells)


def clean(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def parse_spec(src: str) -> tuple[list[dict[str, object]], dict[str, str]]:
    """Return (records, sections) where sections maps filename -> markdown."""
    lines = src.splitlines()
    records: list[dict[str, object]] = []
    sections: dict[str, list[str]] = {}
    seen: set[str] = set()

    current_file = "00-front-matter.md"
    headings: dict[int, str] = {}
    in_fence = False
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if stripped.startswith("```"):
            in_fence = not in_fence
        if not in_fence:
            m = re.match(r"^(#{2,4})\s+(.*)$", line)
            if m:
                level = len(m.group(1))
                if level == 2 and (
                    re.match(r"^\d+\.\s", m.group(2)) or m.group(2).startswith("Appendix")
                ):
                    current_file = section_filename(line)
                headings = {k: v for k, v in headings.items() if k < level}
                headings[level] = clean(m.group(2))
        sections.setdefault(current_file, []).append(line)

        # Table detection: header row followed by a separator row.
        if (
            not in_fence
            and stripped.startswith("|")
            and i + 1 < len(lines)
            and is_separator(lines[i + 1])
        ):
            header = [h.lower() for h in split_cells(line)]
            sections[current_file].append(lines[i + 1])
            j = i + 2
            while j < len(lines) and lines[j].strip().startswith("|"):
                row = split_cells(lines[j])
                sections[current_file].append(lines[j])
                if row and FULL_ID_RE.match(row[0]):
                    rec = build_record(row, header, headings, current_file)
                    rid = str(rec["id"])
                    if rid in seen:
                        raise SystemExit(f"Duplicate ID in spec: {rid}")
                    seen.add(rid)
                    records.append(rec)
                j += 1
            i = j
            continue
        i += 1

    rendered = {
        name: GENERATED_NOTE + "\n".join(body).strip() + "\n" for name, body in sections.items()
    }
    return records, rendered


def build_record(
    row: list[str], header: list[str], headings: dict[int, str], section_file: str
) -> dict[str, object]:
    rid = row[0]
    rec: dict[str, object] = {"id": rid, "kind": kind_of(rid)}
    if rec["kind"] in {"FR", "NFR"}:
        rec["area"] = rid.split("-")[1]
    for name, value in zip(header, row, strict=False):
        key = HEADER_KEYS.get(name)
        if key and key != "id":
            rec[key] = clean(value)
    if rec["kind"] == "G":
        text = str(rec.get("text", ""))
        m = re.match(r"^\*\*(.+?)\.?\*\*\s*(.*)$", text)
        if m:
            rec["title"] = m.group(1).rstrip(".")
            rec["text"] = m.group(2)
    for key in ("text", "reason", "mitigation", "proposed", "pass_condition"):
        if key in rec:
            rec[key] = str(rec[key]).replace("**", "")
    heading = headings.get(4) or headings.get(3) or headings.get(2) or ""
    rec["section"] = heading
    rec["section_file"] = f"docs/spec/sections/{section_file}"
    blob = " ".join(str(v) for k, v in rec.items() if k not in {"id", "section", "section_file"})
    refs = sorted({r for r in ID_RE.findall(blob) if r != rid})
    if refs:
        rec["refs"] = refs
    return rec


# --------------------------------------------------------------------------- build


def cmd_build(args: argparse.Namespace) -> int:
    if not SPEC_SRC.exists():
        print(f"Spec not found: {SPEC_SRC.relative_to(ROOT)}", file=sys.stderr)
        return 1
    records, sections = parse_spec(SPEC_SRC.read_text(encoding="utf-8"))
    index_text = "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in records)
    readme = (
        "# Generated spec files\n\n"
        + GENERATED_NOTE
        + "- `requirements.jsonl`: one record per ID (FR, NFR, INV, G, DP, AS, CN, DD, R, OQ).\n"
        '  Look one up with `python3 scripts/spec_tools.py show <ID>` or `grep \'"id": "<ID>"\'`.\n'
        "- `sections/`: the spec split by top-level section. Read only the section you need.\n"
    )
    wanted: dict[Path, str] = {INDEX: index_text, SPEC_DIR / "README.md": readme}
    for name, body in sections.items():
        wanted[SECTIONS / name] = body

    if args.check:
        stale = [
            p
            for p, body in wanted.items()
            if not p.exists() or p.read_text(encoding="utf-8") != body
        ]
        extra = [p for p in SECTIONS.glob("*.md") if p not in wanted] if SECTIONS.exists() else []
        if stale or extra:
            for p in stale + extra:
                print(f"stale: {p.relative_to(ROOT)}", file=sys.stderr)
            print("Run: python3 scripts/spec_tools.py build", file=sys.stderr)
            return 1
        print("Generated spec files are up to date.")
        return 0

    SECTIONS.mkdir(parents=True, exist_ok=True)
    for p in SECTIONS.glob("*.md"):
        if p not in wanted:
            p.unlink()
    for p, body in wanted.items():
        tmp = p.with_suffix(p.suffix + ".tmp")
        tmp.write_text(body, encoding="utf-8")
        tmp.replace(p)
    counts: dict[str, int] = {}
    for r in records:
        counts[str(r["kind"])] = counts.get(str(r["kind"]), 0) + 1
    summary = ", ".join(f"{k} {v}" for k, v in sorted(counts.items()))
    print(f"Wrote {len(records)} records ({summary}) and {len(sections)} section files.")
    return 0


# --------------------------------------------------------------------------- queries


def load_index() -> list[dict[str, object]]:
    if not INDEX.exists():
        raise SystemExit(
            "docs/spec/requirements.jsonl is missing. Run: python3 scripts/spec_tools.py build"
        )
    with INDEX.open(encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def load_milestones() -> dict[str, dict[str, object]]:
    if not MILESTONES.exists():
        return {}
    data = json.loads(MILESTONES.read_text(encoding="utf-8"))
    return {k: v for k, v in data.items() if not k.startswith("_")}


def milestone_of(rid: str, milestones: dict[str, dict[str, object]]) -> str | None:
    for name in sorted(milestones):
        patterns = milestones[name].get("include", [])
        assert isinstance(patterns, list)
        if any(fnmatch.fnmatchcase(rid, str(p)) for p in patterns):
            return name
    return None


def select(records: Iterable[dict[str, object]], patterns: list[str]) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    records = list(records)
    for pat in patterns:
        matched = [r for r in records if fnmatch.fnmatchcase(str(r["id"]), pat)]
        if not matched:
            print(f"No record matches {pat}", file=sys.stderr)
        out.extend(m for m in matched if m not in out)
    return out


def scan_test_markers() -> dict[str, set[str]]:
    """Static scan: requirement ID -> test files that mention it in a req marker."""
    found: dict[str, set[str]] = {}
    if not TESTS.exists():
        return found
    marker = re.compile(r"mark\.req\(([^)]*)\)", re.DOTALL)
    for path in TESTS.rglob("*.py"):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in marker.finditer(text):
            for rid in ID_RE.findall(m.group(1)):
                found.setdefault(rid, set()).add(str(path.relative_to(ROOT)))
    return found


def load_results() -> dict[str, dict[str, str]]:
    if not RESULTS.exists():
        return {}
    try:
        data = json.loads(RESULTS.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def status_of(rid: str, markers: dict[str, set[str]], results: dict[str, dict[str, str]]) -> str:
    outcomes = results.get(rid, {})
    if outcomes:
        states = set(outcomes.values())
        if states <= {"passed"}:
            return "passing"
        if "failed" in states or "error" in states or "xpass" in states:
            return "failing"
        return "pending"  # xfail or skipped only
    if rid in markers:
        return "tests-not-run"
    return "no-tests"


def needs_tests(rec: dict[str, object]) -> bool:
    if rec["kind"] in {"INV", "G"}:
        return True
    return "T" in str(rec.get("verification", ""))


def one_line(rec: dict[str, object], width: int | None) -> str:
    tag = ""
    if "priority" in rec:
        tag = f" [{rec['priority']}|{rec.get('verification', '')}]"
    text = str(rec.get("title", "")) + (": " if rec.get("title") else "") + str(rec.get("text", ""))
    line = f"{rec['id']}{tag} {text}"
    if width and len(line) > width:
        line = line[: width - 3] + "..."
    return line


def cmd_show(args: argparse.Namespace) -> int:
    records = load_index()
    by_id = {str(r["id"]): r for r in records}
    chosen = select(records, args.ids)
    if args.refs:
        extra: list[dict[str, object]] = []
        for rec in chosen:
            for ref in rec.get("refs", []) or []:
                target = by_id.get(str(ref))
                if target and target not in chosen and target not in extra:
                    extra.append(target)
        chosen += extra
    markers, results = scan_test_markers(), load_results()
    milestones = load_milestones()
    for rec in chosen:
        rid = str(rec["id"])
        print(one_line(rec, None))
        for key, label in (
            ("pass_condition", "pass when"),
            ("likelihood", "likelihood"),
            ("impact", "impact"),
            ("reason", "reason"),
            ("proposed", "proposed"),
            ("mitigation", "mitigation"),
        ):
            if key in rec:
                print(f"  {label}: {rec[key]}")
        print(f"  section: {rec['section']} ({rec['section_file']})")
        ms = milestone_of(rid, milestones)
        if ms:
            print(f"  milestone: {ms}")
        if rec.get("refs"):
            print(f"  refs: {' '.join(map(str, rec['refs']))}")  # type: ignore[arg-type]
        if rec["kind"] in COVERAGE_KINDS:
            print(f"  status: {status_of(rid, markers, results)}")
            for nodeid, state in sorted(results.get(rid, {}).items()):
                print(f"    {state}: {nodeid}")
            if rid in markers and rid not in results:
                print(f"    marked in: {', '.join(sorted(markers[rid]))}")
    return 0 if chosen else 1


def cmd_list(args: argparse.Namespace) -> int:
    records = load_index()
    milestones = load_milestones()
    for rec in records:
        rid = str(rec["id"])
        if args.kind and rec["kind"] != args.kind:
            continue
        if args.area and rec.get("area") != args.area:
            continue
        if (
            args.priority
            and rec.get("priority", "M" if rec["kind"] in {"INV", "G"} else None) != args.priority
        ):
            continue
        if args.milestone and milestone_of(rid, milestones) != args.milestone:
            continue
        print(one_line(rec, None if args.full else 120))
    return 0


def cmd_coverage(args: argparse.Namespace) -> int:
    records = [r for r in load_index() if r["kind"] in COVERAGE_KINDS]
    milestones = load_milestones()
    markers, results = scan_test_markers(), load_results()
    priorities = set(args.priority.split(","))

    def in_scope(rec: dict[str, object]) -> bool:
        prio = str(rec.get("priority", "M"))
        return prio in priorities

    if args.summary:
        names = [*sorted(milestones), "unassigned"]
        for name in names:
            recs = [
                r
                for r in records
                if in_scope(r) and (milestone_of(str(r["id"]), milestones) or "unassigned") == name
            ]
            if not recs:
                continue
            counts: dict[str, int] = {}
            for r in recs:
                key = (
                    status_of(str(r["id"]), markers, results)
                    if needs_tests(r)
                    else "evidence-needed"
                )
                counts[key] = counts.get(key, 0) + 1
            label = (
                milestones.get(name, {}).get("name", "") if name != "unassigned" else "not mapped"
            )
            detail = ", ".join(f"{k} {v}" for k, v in sorted(counts.items()))
            print(f"{name} {label}: {len(recs)} in scope ({detail})")
        return 0

    scope = [
        r
        for r in records
        if in_scope(r)
        and (not args.milestone or milestone_of(str(r["id"]), milestones) == args.milestone)
    ]
    groups: dict[str, list[str]] = {}
    for r in scope:
        rid = str(r["id"])
        key = (
            status_of(rid, markers, results)
            if needs_tests(r)
            else "evidence-needed (verify by I, D or A)"
        )
        groups.setdefault(key, []).append(rid)
    title = f"Milestone {args.milestone}" if args.milestone else "All milestones"
    print(f"{title}, priority {args.priority}: {len(scope)} records")
    order = [
        "failing",
        "no-tests",
        "tests-not-run",
        "pending",
        "passing",
        "evidence-needed (verify by I, D or A)",
    ]
    for key in order:
        ids = groups.get(key, [])
        if not ids:
            continue
        print(f"\n{key} ({len(ids)}):")
        if key == "failing":
            for rid in ids:
                bad = [
                    n
                    for n, s in sorted(results.get(rid, {}).items())
                    if s in {"failed", "error", "xpass"}
                ]
                print(f"  {rid}: {'; '.join(bad)}")
        else:
            print("  " + " ".join(ids))
    if not RESULTS.exists():
        print("\nNo test results recorded yet. Run the tests to populate var/req_results.json.")
    return 1 if groups.get("failing") else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_build = sub.add_parser("build", help="regenerate docs/spec from spec-src")
    p_build.add_argument("--check", action="store_true", help="exit 1 if generated files are stale")
    p_build.set_defaults(func=cmd_build)

    p_show = sub.add_parser("show", help="print records by ID or glob")
    p_show.add_argument("ids", nargs="+")
    p_show.add_argument("--refs", action="store_true", help="also print records the text refers to")
    p_show.set_defaults(func=cmd_show)

    p_list = sub.add_parser("list", help="one line per record")
    p_list.add_argument(
        "--kind", choices=["FR", "NFR", "INV", "G", "DP", "AS", "CN", "DD", "R", "OQ"]
    )
    p_list.add_argument("--area", help="three-letter area, e.g. EXT")
    p_list.add_argument("--priority", choices=["M", "S", "C", "W"])
    p_list.add_argument("--milestone", help="e.g. M1 (uses docs/milestones.json)")
    p_list.add_argument("--full", action="store_true", help="do not truncate lines")
    p_list.set_defaults(func=cmd_list)

    p_cov = sub.add_parser("coverage", help="test coverage by requirement")
    p_cov.add_argument("--milestone", help="e.g. M1")
    p_cov.add_argument("--priority", default="M", help="comma-separated, default M")
    p_cov.add_argument("--summary", action="store_true", help="one line per milestone")
    p_cov.set_defaults(func=cmd_coverage)

    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BrokenPipeError:  # output piped into head or similar
        sys.stdout = open(os.devnull, "w")  # noqa: SIM115
        sys.exit(0)
